apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: erzpcjoze-go 
  janus-idp.io/tekton: erzpcjoze-go
  backstage.io/kubernetes-id: erzpcjoze-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: erzpcjoze-go
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  